#!/bin/bash

set -eux
set -o pipefail

case "${REG_METHOD:-}" in
    portal|satellite)
        # Allow unregistration to fail.
        # We don't want to fail stack deletes if unregistration fails.
        subscription-manager unregister || true
        subscription-manager clean || true
        ;;
    disable)
        echo "Disabling RHEL unregistration"
        ;;
    *)
        echo "WARNING: only 'portal', 'satellite', and 'disable' are valid values for REG_METHOD."
        exit 0
esac
